workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "io.nekohasekai.sfa"
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          echo "ndk.dir=$ANDROID_NDK_HOME" >> "$CM_BUILD_DIR/local.properties"
      
      - name: Install Android SDK components
        script: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-35" "build-tools;35.0.0" "ndk;27.2.12479018"
      
      - name: Generate debug keystore
        script: |
          keytool -genkeypair \
            -alias androiddebugkey \
            -keypass android \
            -keystore debug.keystore \
            -storepass android \
            -dname 'CN=Android Debug,O=Android,C=US' \
            -keyalg 'RSA' \
            -keysize 2048 \
            -validity 10000
      
      - name: Build Android release
        script: |
          ./gradlew assembleDebug

      - name: Build Android TV release
        script: |
          ./gradlew assembleOtherDebug
    
    artifacts:
      - app/build/outputs/apk/play/debug/*.apk
      - app/build/outputs/apk/other/debug/*.apk

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true

  android-tv-workflow:
    name: Android TV Build
    max_build_duration: 60
    environment:
      java: 17
      vars:
        PACKAGE_NAME: "io.nekohasekai.sfa"
    scripts:
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          echo "ndk.dir=$ANDROID_NDK_HOME" >> "$CM_BUILD_DIR/local.properties"
      
      - name: Install Android SDK components
        script: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platforms;android-35" "build-tools;35.0.0" "ndk;27.2.12479018"
      
      - name: Generate debug keystore
        script: |
          keytool -genkeypair \
            -alias androiddebugkey \
            -keypass android \
            -keystore debug.keystore \
            -storepass android \
            -dname 'CN=Android Debug,O=Android,C=US' \
            -keyalg 'RSA' \
            -keysize 2048 \
            -validity 10000
      
      - name: Build Android TV release
        script: |
          ./gradlew assembleOtherDebug
    
    artifacts:
      - app/build/outputs/apk/other/debug/*.apk

    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true